title: Hans Jerry Illikainen
highlighter: rouge
safe: true

collections:
  advisories:
    output: true

defaults:
  - scope:
      path: ""
      type: "advisories"
    values:
      layout: "item"
      feed: true

plugins:
  - jekyll-redirect-from
  - jekyll-titles-from-headings

titles_from_headings:
  collections: true
  strip_title: true

exclude:
  - CNAME
