title: Hans Jerry Illikainen
email: hji@dyntopia.com
github: illikainen
url: https://illikainen.dev

highlighter: rouge
safe: true

collections:
  advisories:
    output: true
    permalink: /:collection/:name
  blog:
    output: true
    permalink: /:collection/:name
  exploits:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "advisories"
    values:
      layout: "item"
      feed: true
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "item"
      feed: true
  - scope:
      path: ""
      type: "exploits"
    values:
      layout: "item"
      feed: true

plugins:
  - jekyll-redirect-from
  - jekyll-titles-from-headings

titles_from_headings:
  collections: true
  strip_title: true

exclude:
  - CNAME
